Drop -isystem libcxx in clang wrapper
This causes cc -v to fail with
```
lang version 11.1.0
Target: aarch64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/v6iidz79b425hli98g45xq9iblapn1zy-clang-11.1.0/bin
 "/nix/store/b82mvqzvdx5mh1n9n77v8h5vk9fgqrxj-clang-wrapper-11.1.0/bin/ld" -demangle -lto_library /nix/store/v6iidz79b425hli98g45xq9iblapn1zy-clang-11.1.0/lib/libLTO.dylib -dynamic -arch arm64 -platform_version macos 11.0.0 0.0.0 -o a.out -L/nix/store/hc8a94w57ppwmn2gscm56pvlwi3zhyh1-libSystem-11.0.0/lib -L/nix/store/6f5ygwif1r523jj2qfwfiwix0fga4rgp-clang-11.1.0-lib/lib -L/nix/store/7pkxnbhpi0c10w18rirj8zxz3wv571nj-libcxx-11.1.0/lib -no_uuid -arch arm64 -lSystem /nix/store/b82mvqzvdx5mh1n9n77v8h5vk9fgqrxj-clang-wrapper-11.1.0/resource-root/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
```